{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vllm-basic.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: &host {{ include "vllm-basic.name" . }}.{{ .Values.ingress.orgID }}-{{ .Values.ingress.clusterName }}.coreweave.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vllm-basic.fullname" . }}
                port:
                  number: {{ .Values.service.port.port }}
  tls:
    - hosts:
        - *host
      secretName: {{ include "vllm-basic.fullname" . }}-tls
{{- end }}
---
